name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
# Step 1: Checkout repo 
      - name: Checkout code
        uses: actions/Checkout@v4

# Step 2: Set up python
      - name: Set up Python 
        uses: actions/setip-python@v5
        with:
          python-verson: '3.12'

# Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip intall --upgrade pip
          pip intstall -r requirements.txt

# Step 45: Lint with flakes8
      - name: Run tests
        run: |
          pip install pytest
          pytest -v

# Step 5: Build Dcoker image (for verification only)
      - name: Build Docker image
        run: |
          docker build -t fake_internship:ci-test .

# Step 6: Build Docker as artifact 
      - name: Save Docker image artifact 
        uses: actions/upload-artifact@v4
        with:
          name: streamlit-image
          path: |
            ./Dockerfile


